### ISSUE TITLE
No webpage was found for the web address: http://localhost:29435/swagger/

### ISSUE THREAD

**Issue by datascienceartist** [FabianGosebrink/ASPNETCore-WebAPI-Sample#1]
When this solution is compiled and run, I see following message : 

No webpage was found for the web address: http://localhost:29435/swagger/

**Comment by alaninspace** [comment]
Having the same issue..

**Comment by axeforeverjumo** [comment]
same.

**Comment by axeforeverjumo** [comment]
You must aces to: http://localhost:5000/swagger/

And you are going to see all options referred to "GET, POST, DELETE".

**Comment by beecashco** [comment]
same 
When this solution is compiled and run, I see following message :
No webpage was found for the web address: http://localhost:29435/swagger/

**Comment by alaninspace** [comment]
Am wondering if it’s got something to do with later builds of VS2017..
Maybe this: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/559

**Comment by phanchaulong** [comment]
you must deploy .Net Core application to IIS.
follow this guide.
https://neelbhatt.com/2018/01/30/deploy-net-core-application-to-iis-step-by-step-guide/
I was successful

**Comment by alaninspace** [comment]
@phanchaulong we're not talking about deployment, simply debugging locally via Visual Studio.

**Comment by FabianGosebrink** [comment]
Hey, please take a look. It should be updated now :)

**Comment by nxp2910** [comment]
I just installed Swashbuckle.AspNetCore 3.0.0. It worked for the first time. I was able to access the documentation via http://localhost:58030/swagger Then I removed the ValuesController (default controller in the VS template) and updated the LaunchUrl in launchSettings.json. Since then I have this same issue. No other changes were made and I use Visual Studio 2017.
